[package]
name = "flox"
version = "0.1.0"
authors = ["Trevor Sargent <trevor.a.sargent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex = { path = "../vex" }